// ─── visitor-connection.ts ───────────────────────────────────────────────────
//
// Visitor-side WebRTC connection management.
//
// A visitor with a valid DenKey calls joinDen(denKey) to:
//   1. Subscribe to the signaling channel
//   2. Check the host is online
//   3. Create a WebRTC offer and send a join-request signal
//   4. Receive the host's SDP answer
//   5. Exchange ICE candidates
//   6. Open a data channel and wire scoped Yjs sync
//
// Scope enforcement on the visitor side:
//   - canWrite is derived from denKey.scope.write
//   - For Peek keys (read-only), the visitor's Yjs updates are never sent
//     (wireScopedYjsSync ignores updates when canWrite = false)
//   - For Letterbox keys, see offline-drops.ts (no live WebRTC path)

import * as awarenessProtocol from "y-protocols/awareness";
import { validateKey } from "@meerkat/keys";
import { openDen } from "@meerkat/local-store";
import type { DenKey } from "@meerkat/keys";
import {
  SignalingChannel,
  DEFAULT_ICE_SERVERS,
  signalingChannelName,
} from "./signaling";
import { wireScopedYjsSync } from "./yjs-sync";
import type {
  SyncStatus,
  P2PManagerOptions,
  JoinResponseSignal,
  IceCandidateSignal,
} from "../types";

const DATA_CHANNEL_LABEL = "yjs-sync";
// How long to wait for host-online before sending join-request (host broadcasts every 5s)
const HOST_ONLINE_WAIT_MS = 6_000;
// How long to wait for a join-response before giving up
const HANDSHAKE_TIMEOUT_MS = 15_000;

// ─── VisitorConnection ───────────────────────────────────────────────────────

/**
 * Manages a single visitor's connection to a host den.
 *
 * Lifecycle:
 *   const vc = new VisitorConnection(denKey, hostDenId, options)
 *   await vc.connect(visitorId)   // sends join request, completes handshake
 *   vc.disconnect()               // closes everything
 */
export class VisitorConnection {
  private readonly denKey: DenKey;
  private readonly hostDenId: string;
  private readonly options: P2PManagerOptions;

  private signaling: SignalingChannel | null = null;
  private peer: RTCPeerConnection | null = null;
  private yjsCleanup: (() => void) | null = null;
  private pendingCandidates: RTCIceCandidateInit[] = [];

  private statusHandlers = new Set<(status: SyncStatus) => void>();
  private _status: SyncStatus = "offline";

  constructor(denKey: DenKey, hostDenId: string, options: P2PManagerOptions) {
    this.denKey = denKey;
    this.hostDenId = hostDenId;
    this.options = options;
  }

  // ── Public API ────────────────────────────────────────────────────────────

  get status(): SyncStatus {
    return this._status;
  }

  onStatusChange(handler: (status: SyncStatus) => void): () => void {
    this.statusHandlers.add(handler);
    return () => this.statusHandlers.delete(handler);
  }

  /**
   * Initiate connection to the host den.
   * @param visitorId — Ephemeral ID for this session (generated by the caller).
   */
  async connect(visitorId: string): Promise<void> {
    if (!validateKey(this.denKey)) {
      throw new Error("[@meerkat/p2p] DenKey is invalid or expired");
    }

    this._setStatus("connecting");

    // 1. Subscribe to signaling channel
    const channel = this.options.createSignalingChannel(
      signalingChannelName(this.hostDenId),
    );
    this.signaling = new SignalingChannel(channel, this.hostDenId);

    // 2. Create RTCPeerConnection
    const peer = new RTCPeerConnection({
      iceServers: this.options.iceServers ?? DEFAULT_ICE_SERVERS,
    });
    this.peer = peer;

    // 3. Queue ICE candidates that arrive before answer is set
    peer.onicecandidate = async ({ candidate }) => {
      if (!candidate || !this.signaling?.isConnected) return;
      await this.signaling.sendIceCandidate({
        type: "ice-candidate",
        visitorId,
        denId: this.hostDenId,
        candidate: candidate.toJSON(),
        from: "visitor",
      });
    };

    // 4. Handle disconnection
    peer.onconnectionstatechange = () => {
      if (
        peer.connectionState === "disconnected" ||
        peer.connectionState === "failed" ||
        peer.connectionState === "closed"
      ) {
        this._setStatus("offline");
      }
    };

    // 5. Wait for join-response and ICE candidates
    const responsePromise = this.waitForJoinResponse(visitorId);
    const hostOnlinePromise = this.waitForHostOnline();

    this.signaling.onIceCandidate(async (msg: IceCandidateSignal) => {
      if (msg.from !== "host" || msg.visitorId !== visitorId) return;
      if (peer.remoteDescription) {
        await peer.addIceCandidate(msg.candidate).catch(() => {});
      } else {
        this.pendingCandidates.push(msg.candidate);
      }
    });

    await this.signaling.connect();

    // 5b. Wait for host-online (host broadcasts every 5s) so we don't send into the void
    await hostOnlinePromise;

    // 6. Create and send SDP offer
    const offer = await peer.createOffer();
    await peer.setLocalDescription(offer);

    await this.signaling.sendJoinRequest({
      type: "join-request",
      visitorId,
      denId: this.hostDenId,
      sdpOffer: offer.sdp ?? "",
      denKey: this.denKey,
    });

    // 7. Wait for the response (with timeout)
    const response = await responsePromise;

    if (!response.accepted) {
      this._setStatus("offline");
      throw new Error(
        `[@meerkat/p2p] Join rejected by host: ${response.reason ?? "unknown reason"}`,
      );
    }

    // 8. Set remote description
    await peer.setRemoteDescription({
      type: "answer",
      sdp: response.sdpAnswer,
    });

    // 9. Apply any queued ICE candidates
    for (const c of this.pendingCandidates) {
      await peer.addIceCandidate(c).catch(() => {});
    }
    this.pendingCandidates = [];

    // 10. Wire Yjs sync when data channel opens
    peer.ondatachannel = async (event) => {
      if (event.channel.label !== DATA_CHANNEL_LABEL) return;
      await this.wireYjsSync(event.channel);
    };
  }

  /**
   * Disconnect from the host den and clean up.
   */
  disconnect(): void {
    this.yjsCleanup?.();
    this.yjsCleanup = null;

    this.peer?.close();
    this.peer = null;

    this.signaling?.disconnect().catch(() => {});
    this.signaling = null;

    this._setStatus("offline");
  }

  // ── Private ───────────────────────────────────────────────────────────────

  private waitForHostOnline(): Promise<void> {
    return new Promise((resolve) => {
      const timeout = setTimeout(resolve, HOST_ONLINE_WAIT_MS);
      this.signaling?.onHostOnline(() => {
        clearTimeout(timeout);
        resolve();
      });
    });
  }

  private waitForJoinResponse(visitorId: string): Promise<JoinResponseSignal> {
    return new Promise((resolve, reject) => {
      const timeout = setTimeout(() => {
        reject(
          new Error(
            `[@meerkat/p2p] Handshake timed out waiting for join-response (${HANDSHAKE_TIMEOUT_MS}ms)`,
          ),
        );
      }, HANDSHAKE_TIMEOUT_MS);

      this.signaling?.onJoinResponse((msg: JoinResponseSignal) => {
        if (msg.visitorId !== visitorId) return;
        clearTimeout(timeout);
        resolve(msg);
      });
    });
  }

  private async wireYjsSync(channel: RTCDataChannel): Promise<void> {
    try {
      const { sharedDen } = await openDen(this.hostDenId);
      const awareness = new awarenessProtocol.Awareness(sharedDen.ydoc);

      this.yjsCleanup = wireScopedYjsSync({
        ydoc: sharedDen.ydoc,
        channel,
        awareness,
        canWrite: this.denKey.scope.write,
        role: "visitor",
      });

      this._setStatus("synced");
    } catch (err) {
      console.error("[@meerkat/p2p] Failed to wire Yjs sync on visitor:", err);
      this.disconnect();
    }
  }

  private _setStatus(next: SyncStatus): void {
    if (next === this._status) return;
    this._status = next;
    for (const handler of this.statusHandlers) {
      try {
        handler(next);
      } catch (err) {
        console.error("[@meerkat/p2p] Status handler threw:", err);
      }
    }
  }
}
